name: CI/CD Pipeline for Chat App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/chat-app:latest \
            -f ./app/Dockerfile \
            ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull himanshu3179/chat-app:latest
            sudo docker stop chat-app || true
            sudo docker rm chat-app || true
            sudo docker run -d \
              --name chat-app \
              -p 80:80 \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              himanshusingh3179/chat-app:latest
            echo "Deployment script finished. Your application should now be live on http://${{ secrets.SSH_HOST }}"